name: Deploy to Azure Functions

on:
  push:
    branches:
      - main  # Change this to the branch you want to deploy from
      - testing-branch  # Add your testing branch here if needed

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'  # Ensure this matches your function app's runtime

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Azure Functions Action
        uses: Azure/functions-action@v1
        with:
          app-name: FishingChatbotFunction
          package: '.'
          publish-profile: ${{ secrets.AZURE_FUNCTIONS_PUBLISH_PROFILE }}
